events { worker_connections 1024; }
http {
    include mime.types;
    server {
        listen 80;

        # Cấu hình phục vụ video segments (Task 1.5)
        location /video/ {
            alias /usr/share/nginx/html/video/;
            add_header Access-Control-Allow-Origin *; # Cho phép Player truy cập
        }

        # Điều hướng yêu cầu License sang Backend
        location /license {
            proxy_pass http://license-server:3000;
            add_header Cache-Control "no-store"; # Tuyệt đối không cache Key
        }
    }
}