#!/usr/bin/env bash
set -euo pipefail

HOSTNAME="${1:-cdn.local}"
CERT_DIR="${2:-/etc/nt219/certs}"
SNIPPET_PATH="${3:-/etc/nginx/snippets/nt219-cert-pin.conf}"

CERT_PATH="${CERT_DIR}/fullchain.pem"
KEY_PATH="${CERT_DIR}/privkey.pem"
PIN_PATH="${CERT_DIR}/pin.sha256.txt"

sudo mkdir -p "$CERT_DIR" "$(dirname "$SNIPPET_PATH")"

if [[ ! -f "$CERT_PATH" || ! -f "$KEY_PATH" ]]; then
    echo "[cert-pin] No certificate found in ${CERT_DIR}; generating self-signed cert for ${HOSTNAME}."
    sudo openssl req -x509 -nodes -newkey rsa:2048 \
        -keyout "$KEY_PATH" \
        -out "$CERT_PATH" \
        -days 365 \
        -subj "/C=VN/ST=HCM/O=NT219/OU=vm/CN=${HOSTNAME}" \
        -addext "subjectAltName=DNS:${HOSTNAME},DNS:localhost,IP:127.0.0.1" \
        >/dev/null 2>&1
    sudo chmod 600 "$KEY_PATH"
fi

PIN_VALUE="$(
    openssl x509 -in "$CERT_PATH" -pubkey -noout \
        | openssl pkey -pubin -outform DER \
        | openssl dgst -sha256 -binary \
        | openssl base64 -A
)"

printf 'sha256-%s\n' "$PIN_VALUE" | sudo tee "$PIN_PATH" >/dev/null

sudo tee "$SNIPPET_PATH" >/dev/null <<EOF
# Generated by infra/vm/generate-cert-pin.sh.
map \$host \$cdn_cert_pin {
    default "sha256-${PIN_VALUE}";
}
EOF

echo "[cert-pin] Wrote ${PIN_PATH}"
echo "[cert-pin] Wrote ${SNIPPET_PATH}"
